export const bodyAreas = [
  { id: 'knee', name: 'Knee', emoji: '🦵', color: '#4CAF50' },
  { id: 'hip', name: 'Hip', emoji: '🦿', color: '#2196F3' },
  { id: 'shoulder', name: 'Shoulder', emoji: '💪', color: '#FF9800' },
  { id: 'ankle', name: 'Ankle', emoji: '🦶', color: '#9C27B0' },
  { id: 'back', name: 'Back', emoji: '🧘', color: '#F44336' },
  { id: 'wrist', name: 'Wrist', emoji: '✋', color: '#00BCD4' },
];

export const exercises = {
  knee: [
    {
      id: 'knee1',
      name: 'Straight Leg Raises',
      description: 'Strengthen your quadriceps without bending the knee',
      duration: '2 min',
      difficulty: 'Easy',
      youtubeId: 'fLoDguKIPiQ',
      sets: '3 sets of 10 reps',
    },
    {
      id: 'knee2',
      name: 'Quad Sets',
      description: 'Simple exercise to activate quadriceps muscles',
      duration: '1 min',
      difficulty: 'Easy',
      youtubeId: 'sjVW6d0kOr8',
      sets: '3 sets of 15 reps',
    },
    {
      id: 'knee3',
      name: 'Hamstring Curls',
      description: 'Strengthen hamstrings safely',
      duration: '2 min',
      difficulty: 'Easy',
      youtubeId: 'nYE1lJ0n2SQ',
      sets: '3 sets of 10 reps',
    },
    {
      id: 'knee4',
      name: 'Heel Slides',
      description: 'Improve knee flexion range of motion',
      duration: '2 min',
      difficulty: 'Easy',
      youtubeId: 'gocGK5ZH3ZM',
      sets: '3 sets of 10 reps',
    },
    {
      id: 'knee5',
      name: 'Wall Squats',
      description: 'Build strength in quads and glutes',
      duration: '3 min',
      difficulty: 'Medium',
      youtubeId: 'y-wV4Venusw',
      sets: '3 sets of 8 reps',
    },
  ],
  hip: [
    {
      id: 'hip1',
      name: 'Hip Flexion',
      description: 'Improve hip mobility and strength',
      duration: '2 min',
      difficulty: 'Easy',
      youtubeId: 'UGEpQ1BRx-4',
      sets: '3 sets of 10 reps',
    },
    {
      id: 'hip2',
      name: 'Hip Abduction',
      description: 'Strengthen hip abductor muscles',
      duration: '2 min',
      difficulty: 'Easy',
      youtubeId: 'kJkVhAaBA6I',
      sets: '3 sets of 10 reps',
    },
    {
      id: 'hip3',
      name: 'Glute Bridges',
      description: 'Strengthen glutes and hamstrings',
      duration: '3 min',
      difficulty: 'Medium',
      youtubeId: 'wPM8icPu6H8',
      sets: '3 sets of 12 reps',
    },
    {
      id: 'hip4',
      name: 'Clamshells',
      description: 'Target hip external rotators',
      duration: '2 min',
      difficulty: 'Easy',
      youtubeId: 'ZM6GLNGAlik',
      sets: '3 sets of 15 reps',
    },
    {
      id: 'hip5',
      name: 'Standing Hip Extension',
      description: 'Strengthen posterior hip muscles',
      duration: '2 min',
      difficulty: 'Easy',
      youtubeId: 'BLqzIicSgcM',
      sets: '3 sets of 10 reps',
    },
  ],
  shoulder: [
    {
      id: 'shoulder1',
      name: 'Pendulum Exercises',
      description: 'Gentle shoulder mobility exercise',
      duration: '2 min',
      difficulty: 'Easy',
      youtubeId: 'nqXEqWYu3CA',
      sets: '5 minutes daily',
    },
    {
      id: 'shoulder2',
      name: 'Shoulder Blade Squeeze',
      description: 'Strengthen upper back muscles',
      duration: '1 min',
      difficulty: 'Easy',
      youtubeId: 'x1hY8G8p5Do',
      sets: '3 sets of 15 reps',
    },
    {
      id: 'shoulder3',
      name: 'Wall Walks',
      description: 'Improve shoulder flexion range',
      duration: '2 min',
      difficulty: 'Easy',
      youtubeId: 'h-YJsUl63Fw',
      sets: '3 sets of 10 reps',
    },
    {
      id: 'shoulder4',
      name: 'External Rotation',
      description: 'Strengthen rotator cuff muscles',
      duration: '2 min',
      difficulty: 'Medium',
      youtubeId: 'VsINsz0CL5E',
      sets: '3 sets of 10 reps',
    },
    {
      id: 'shoulder5',
      name: 'Scapular Setting',
      description: 'Improve shoulder blade control',
      duration: '1 min',
      difficulty: 'Easy',
      youtubeId: 'xQ1cJOjZuzw',
      sets: '3 sets of 15 reps',
    },
  ],
  ankle: [
    {
      id: 'ankle1',
      name: 'Ankle Pumps',
      description: 'Basic ankle movement exercise',
      duration: '2 min',
      difficulty: 'Easy',
      youtubeId: 'uTJ8ZWQr6lQ',
      sets: '3 sets of 20 reps',
    },
    {
      id: 'ankle2',
      name: 'Alphabet Exercises',
      description: 'Improve ankle range of motion',
      duration: '3 min',
      difficulty: 'Easy',
      youtubeId: '8xdJEZdwqbE',
      sets: 'A to Z twice daily',
    },
    {
      id: 'ankle3',
      name: 'Calf Raises',
      description: 'Strengthen calf muscles',
      duration: '2 min',
      difficulty: 'Medium',
      youtubeId: 'gwLzBJYoWlI',
      sets: '3 sets of 15 reps',
    },
    {
      id: 'ankle4',
      name: 'Ankle Circles',
      description: 'Improve ankle mobility',
      duration: '2 min',
      difficulty: 'Easy',
      youtubeId: 'BE3MQON-qoI',
      sets: '10 circles each direction',
    },
    {
      id: 'ankle5',
      name: 'Towel Stretch',
      description: 'Stretch calf and improve flexibility',
      duration: '2 min',
      difficulty: 'Easy',
      youtubeId: 'XKgUV_NqRps',
      sets: 'Hold 30 seconds, 3 times',
    },
  ],
  back: [
    {
      id: 'back1',
      name: 'Cat-Cow Stretch',
      description: 'Improve spine flexibility',
      duration: '2 min',
      difficulty: 'Easy',
      youtubeId: 'kqnua4rHVVA',
      sets: '10 repetitions',
    },
    {
      id: 'back2',
      name: 'Pelvic Tilts',
      description: 'Strengthen core and lower back',
      duration: '2 min',
      difficulty: 'Easy',
      youtubeId: '6MsEcEqXcco',
      sets: '3 sets of 10 reps',
    },
    {
      id: 'back3',
      name: 'Knee to Chest',
      description: 'Stretch lower back muscles',
      duration: '2 min',
      difficulty: 'Easy',
      youtubeId: 'MivqK2I5M4w',
      sets: 'Hold 30 seconds each',
    },
    {
      id: 'back4',
      name: 'Bird Dog',
      description: 'Core stability exercise',
      duration: '3 min',
      difficulty: 'Medium',
      youtubeId: 'wiFNA3sqjCA',
      sets: '3 sets of 10 reps each side',
    },
    {
      id: 'back5',
      name: 'Bridge Exercise',
      description: 'Strengthen glutes and lower back',
      duration: '2 min',
      difficulty: 'Easy',
      youtubeId: 'wPM8icPu6H8',
      sets: '3 sets of 12 reps',
    },
  ],
  wrist: [
    {
      id: 'wrist1',
      name: 'Wrist Flexion Stretch',
      description: 'Improve wrist flexibility',
      duration: '1 min',
      difficulty: 'Easy',
      youtubeId: 'fdD7CgN5FGg',
      sets: 'Hold 30 seconds, 3 times',
    },
    {
      id: 'wrist2',
      name: 'Wrist Extension Stretch',
      description: 'Stretch wrist extensors',
      duration: '1 min',
      difficulty: 'Easy',
      youtubeId: 'UrhH2YeQ70I',
      sets: 'Hold 30 seconds, 3 times',
    },
    {
      id: 'wrist3',
      name: 'Wrist Circles',
      description: 'Improve wrist mobility',
      duration: '2 min',
      difficulty: 'Easy',
      youtubeId: '9RLJZhN3QCQ',
      sets: '10 circles each direction',
    },
    {
      id: 'wrist4',
      name: 'Grip Strengthening',
      description: 'Build grip strength',
      duration: '2 min',
      difficulty: 'Easy',
      youtubeId: 'lKHi3K0IqbE',
      sets: '3 sets of 10 squeezes',
    },
    {
      id: 'wrist5',
      name: 'Pronation/Supination',
      description: 'Improve forearm rotation',
      duration: '2 min',
      difficulty: 'Easy',
      youtubeId: 'qc7HVRqwSZ4',
      sets: '3 sets of 10 reps',
    },
  ],
};